<?php

return [
    'identity' => [
        'app_name' => 'Barbería Tres Amigos',
        'display_name' => 'BARBERÍA TRES AMIGOS',
        'short_name' => 'Tres Amigos',
        'tagline' => 'Cortes, barba y experiencias premium',
        'subtitle' => 'Tu estilo, tu experiencia',
        'location_short' => 'Puntarenas, Costa Rica',
        'location_full' => 'Puntarenas, El Roble, Costa Rica',
        'rating' => 4.9,
        'review_count' => 128,
        'legal_name' => 'Barbería Tres Amigos S.A.',
    ],
    'assets' => [
        'logo_transparent' => 'assets/branding/logo_transparent.png',
        'logo_dark' => 'assets/branding/logo_dark.png',
        'logo_light' => 'assets/branding/logo_light.png',
        'hero_background' => 'assets/branding/barbershop_hero_bg.png',
        'login_background' => 'assets/branding/barbershop_hero_bg.png',
        'onboarding_background' => 'assets/branding/barbershop_hero_bg.png',
        'service_placeholder' => 'assets/branding/service_placeholder.png',
        'premium_service_placeholder' => 'assets/branding/service_placeholder_premium.png',
        'staff_placeholder' => 'assets/branding/barber_placeholder.png',
        'profile_placeholder' => 'assets/branding/profile_placeholder.png',
        'app_icon' => 'assets/branding/app_icon.png',
    ],
    'colors' => [
        'primary' => '#D4A84F',
        'primary_light' => '#E8C36A',
        'primary_dark' => '#9B6F24',
        'secondary' => '#E8D8B8',
        'accent' => '#B77A3E',
        'background' => '#090909',
        'surface' => '#1A1512',
        'card' => '#120E0B',
        'border' => '#22FFFFFF',
        'text_primary' => '#FFFFFF',
        'text_secondary' => '#B9AFA5',
        'text_on_primary' => '#090909',
        'success' => '#04B155',
        'warning' => '#FFC107',
        'danger' => '#EB3B5A',
        'primary_gold' => '#D4A84F',
        'primary_gold_light' => '#E8C36A',
        'primary_gold_dark' => '#9B6F24',
    ],
    'appearance' => [
        'theme_mode' => 'dark',
        'theme_preset' => 'barber_luxury',
        'card_radius' => 24,
        'input_radius' => 18,
        'button_radius' => 18,
        'use_cinematic_backgrounds' => true,
        'use_logo_glow' => true,
        'use_heavy_blur' => false,
    ],
    'contact' => [
        'phone' => '+506 8888-3366',
        'whatsapp' => '+506 8888-3366',
        'email' => 'hola@barberiatresamigos.com',
        'instagram' => '@barberiatresamigos',
        'facebook' => 'Barbería Tres Amigos',
        'website' => 'https://barberiatresamigos.com',
        'address' => 'Puntarenas, El Roble, Costa Rica',
    ],
    'hours' => [
        'label' => 'Horario de atención',
        'weekly_summary' => "Lun 10:00 AM - 7:00 PM\nMar - Jue 10:00 AM - 12:00 PM / 2:00 PM - 8:00 PM\nVie - Sáb 10:00 AM - 7:00 PM\nDomingo cerrado",
        'detailed_hours' => [
            'Lun 10:00 AM - 7:00 PM',
            'Mar - Jue 10:00 AM - 12:00 PM / 2:00 PM - 8:00 PM',
            'Vie - Sáb 10:00 AM - 7:00 PM',
            'Domingo cerrado',
        ],
    ],
    'policies' => [
        'cancellation_window_hours' => 4,
        'cancellation_policy_text' => 'Podés cancelar o reprogramar hasta 4 horas antes de tu cita.',
    ],
    'terminology' => [
        'business' => 'negocio',
        'business_profile' => 'perfil de la barbería',
        'service' => 'servicio',
        'services' => 'servicios',
        'appointment' => 'cita',
        'appointments' => 'citas',
        'staff' => 'barbero',
        'staff_plural' => 'barberos',
        'staff_display_name' => 'barbero',
        'manager' => 'administrador',
        'gallery' => 'galería',
        'reviews' => 'opiniones',
    ],
    'features' => [
        'show_staff' => true,
        'reservation_staff_selection' => true,
        'admin_staff_management' => true,
        'show_gallery' => true,
        'show_reviews' => true,
        'show_business_profile' => true,
        'show_admin_dashboard' => true,
    ],
];
