@php
    $isOwnerApp = ($experience ?? 'b') === 'app';
    $resolvedBrand = \App\Support\BrandingConfig::resolveForBusiness($business);
    $primary = data_get($resolvedBrand, 'colors.primary', '#D4A84F');
@endphp
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
    <meta name="theme-color" content="{{ $isOwnerApp ? '#090909' : $primary }}">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="manifest" href="{{ route('pwa.manifest', ['experience' => $experience ?? 'b', 'slug' => $business->slug]) }}">
    <link rel="apple-touch-icon" href="{{ route('pwa.icon', ['slug' => $business->slug, 'size' => 192]) }}">
    @if($isOwnerApp)
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
    @endif
    <title>@yield('title', $business->name)</title>
    <style>
        @font-face{font-family:"Material Symbols Rounded";font-style:normal;font-weight:100 700;font-display:block;src:url("{{ asset('assets/fonts/material-symbols-rounded.woff2') }}") format("woff2")}
        :root{--brand:{{ $primary }};--ink:#0b1220;--muted:#64748b;--line:#e2e8f0;--paper:#fff;--wash:#f4f7fb;--good:#087f5b;--bad:#c92a2a;--radius:20px;color-scheme:light}
        *{box-sizing:border-box}html{background:var(--wash)}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--ink);background:var(--wash);-webkit-font-smoothing:antialiased}button,input,select{font:inherit}button,a{-webkit-tap-highlight-color:transparent}.shell{width:min(100%,720px);min-height:100dvh;margin:auto;background:var(--paper);padding-bottom:calc(92px + env(safe-area-inset-bottom));box-shadow:0 0 60px rgba(15,23,42,.08)}
        .topbar{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:12px;padding:calc(14px + env(safe-area-inset-top)) 20px 14px;background:rgba(255,255,255,.92);backdrop-filter:blur(16px);border-bottom:1px solid var(--line)}.brandmark{display:grid;place-items:center;width:42px;height:42px;border-radius:14px;background:var(--ink);color:var(--brand);font-weight:900}.topbar h1{font-size:17px;margin:0}.topbar p{font-size:12px;color:var(--muted);margin:2px 0 0}.top-spacer{flex:1}
        main{padding:22px 20px}.eyebrow{color:var(--good);font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.1em}.hero h2{font-size:clamp(28px,8vw,42px);line-height:1.05;letter-spacing:-.04em;margin:8px 0 12px}.hero p{color:var(--muted);line-height:1.6;margin:0}.card{background:#fff;border:1px solid var(--line);border-radius:var(--radius);padding:18px;box-shadow:0 8px 30px rgba(15,23,42,.05)}.stack{display:grid;gap:14px}.grid{display:grid;gap:12px}.grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}
        .choice{display:block;position:relative}.choice input{position:absolute;opacity:0}.choice-body{display:block;height:100%;padding:17px;border:2px solid var(--line);border-radius:18px;background:#fff;transition:.18s;cursor:pointer}.choice input:checked+.choice-body{border-color:var(--brand);box-shadow:0 0 0 4px color-mix(in srgb,var(--brand) 18%,transparent);transform:translateY(-1px)}.choice-title{font-weight:800}.choice-meta{display:flex;justify-content:space-between;gap:8px;color:var(--muted);font-size:13px;margin-top:8px}.avatar{width:48px;height:48px;border-radius:16px;background:var(--ink);color:var(--brand);display:grid;place-items:center;font-weight:900;margin-bottom:10px}
        .button{min-height:50px;border:0;border-radius:16px;padding:13px 18px;font-weight:800;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:8px;text-decoration:none}.button.primary{background:var(--ink);color:#fff}.button.brand{background:var(--brand);color:var(--ink)}.button.secondary{background:#eef2f7;color:var(--ink)}.button.danger{background:#fff1f2;color:var(--bad)}.button.success{background:#ecfdf5;color:var(--good)}.button:disabled{opacity:.45;cursor:not-allowed}.actions{display:flex;gap:10px;margin-top:22px}.actions>*{flex:1}
        .field{display:grid;gap:7px}.field label{font-weight:750;font-size:14px}.field input,.field select{width:100%;min-height:52px;border:1.5px solid var(--line);border-radius:15px;padding:12px 14px;background:#fff;color:var(--ink)}.field input:focus,.field select:focus{outline:3px solid color-mix(in srgb,var(--brand) 24%,transparent);border-color:var(--brand)}.progress{display:flex;gap:6px;margin:18px 0 24px}.progress span{height:5px;flex:1;border-radius:9px;background:var(--line)}.progress span.active{background:var(--brand)}.step[hidden]{display:none}.step h3{font-size:24px;letter-spacing:-.03em;margin:0 0 6px}.step>.hint{color:var(--muted);margin:0 0 18px}.slots{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.slots .choice-body{text-align:center;padding:13px 7px;font-size:14px}.summary{display:grid;gap:12px}.summary-row{display:flex;justify-content:space-between;gap:16px;border-bottom:1px solid var(--line);padding-bottom:12px}.summary-row span{color:var(--muted)}.alert{border-radius:15px;padding:13px 15px;margin-bottom:16px;background:#fff1f2;color:var(--bad)}.status{border-radius:15px;padding:13px 15px;margin-bottom:16px;background:#ecfdf5;color:var(--good)}.empty{text-align:center;padding:34px 18px;color:var(--muted)}
        .bottom-nav{position:fixed;z-index:30;left:50%;bottom:0;transform:translateX(-50%);width:min(100%,720px);display:grid;grid-template-columns:repeat(4,1fr);padding:9px 10px calc(9px + env(safe-area-inset-bottom));background:rgba(255,255,255,.96);backdrop-filter:blur(16px);border-top:1px solid var(--line)}.bottom-nav a{text-decoration:none;color:var(--muted);font-size:11px;font-weight:750;text-align:center;padding:7px 3px;border-radius:12px}.bottom-nav a.active{background:#f1f5f9;color:var(--ink)}.bottom-nav b{display:block;font-size:19px;margin-bottom:2px}.muted{color:var(--muted)}.qr{display:block;width:min(100%,280px);aspect-ratio:1;margin:18px auto;border:12px solid #fff;border-radius:20px}.install-banner{display:none}.install-banner.visible{display:flex}

        body.owner-app{--owner-bg:#090909;--owner-surface:#1a1512;--owner-card:#120e0b;--owner-elevated:#211a15;--owner-line:rgba(255,255,255,.1);--owner-gold-line:color-mix(in srgb,var(--brand) 46%,transparent);--owner-text:#fff;--owner-muted:#b9afa5;--owner-success:#04b155;--owner-warning:#f4b740;--owner-danger:#eb3b5a;color-scheme:dark;background:#050505;color:var(--owner-text);font-family:Roboto,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
        .owner-app .shell{width:min(100%,760px);background:var(--owner-bg);padding-bottom:calc(92px + env(safe-area-inset-bottom));box-shadow:0 0 64px #000;overflow:hidden}.owner-app main{padding:20px 18px 34px}.material-symbols-rounded{font-family:"Material Symbols Rounded";font-weight:normal;font-style:normal;font-size:24px;line-height:1;letter-spacing:normal;text-transform:none;display:inline-block;white-space:nowrap;word-wrap:normal;direction:ltr;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;font-feature-settings:"liga";font-variation-settings:'FILL' 0,'wght' 550,'GRAD' 0,'opsz' 24}
        .owner-app .topbar{padding:calc(10px + env(safe-area-inset-top)) 18px 10px;background:rgba(9,9,9,.92);border:0;backdrop-filter:blur(18px)}.owner-app .brandmark{width:44px;height:44px;border:1px solid var(--owner-gold-line);border-radius:50%;overflow:hidden;background:var(--owner-card)}.owner-app .brandmark img{width:100%;height:100%;object-fit:cover}.owner-app .topbar h1{color:#fff;font-size:16px;font-weight:900;letter-spacing:-.01em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:230px}.owner-app .topbar p{color:var(--owner-muted);font-size:11px;letter-spacing:.08em;text-transform:uppercase}.icon-button{width:44px;height:44px;display:grid;place-items:center;border:1px solid var(--owner-line);border-radius:15px;background:var(--owner-card);color:var(--owner-text);text-decoration:none;cursor:pointer}
        .owner-app .status,.owner-app .alert{margin:8px 18px 0;border:1px solid;color:#fff;background:var(--owner-card)}.owner-app .status{border-color:color-mix(in srgb,var(--owner-success) 45%,transparent)}.owner-app .alert{border-color:color-mix(in srgb,var(--owner-danger) 55%,transparent)}
        .page-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:20px}.page-head .eyebrow,.owner-hero .eyebrow{color:var(--brand);font-size:11px;font-weight:900;letter-spacing:.14em}.page-head h2{font-size:31px;line-height:1.05;letter-spacing:-.04em;margin:6px 0 5px}.page-head p{margin:0;color:var(--owner-muted);font-size:14px;line-height:1.45}.section-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:28px 2px 13px}.section-head h3{margin:0;color:#fff;font-size:20px;letter-spacing:-.025em}.text-link{color:var(--brand);font-weight:700;font-size:13px;text-decoration:none}
        .owner-hero{position:relative;min-height:224px;display:grid;place-items:center;text-align:center;padding:26px 20px;border:1px solid var(--owner-gold-line);border-radius:24px;background:var(--owner-card);overflow:hidden}.owner-hero::after{content:"";position:absolute;inset:8px;border:1px solid rgba(212,168,79,.15);border-radius:18px;pointer-events:none}.hero-logo{position:relative;z-index:1;width:86px;height:86px;border-radius:50%;object-fit:cover;border:1px solid var(--owner-gold-line);background:#0a0908}.owner-hero h2{position:relative;z-index:1;font-size:27px;line-height:1.08;letter-spacing:-.04em;margin:12px 0 5px}.owner-hero p{position:relative;z-index:1;color:var(--owner-muted);font-size:13px;margin:0}.owner-hero .eyebrow{position:relative;z-index:1;margin-top:10px}
        .owner-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:14px}.owner-card{border:1px solid var(--owner-line);border-radius:24px;background:var(--owner-card);padding:17px}.metric-card{min-height:132px;display:flex;flex-direction:column;justify-content:space-between}.metric-icon{width:42px;height:42px;border-radius:14px;background:color-mix(in srgb,var(--brand) 16%,var(--owner-card));color:var(--brand);display:grid;place-items:center}.metric-icon .material-symbols-rounded{font-size:24px;color:var(--brand);margin:0}.metric-card strong{display:block;font-size:30px;line-height:1;font-weight:900;letter-spacing:-.04em}.metric-card>div>span{font-size:12px;color:var(--owner-muted);margin-top:6px;display:block}
        .appointment-list{display:grid;gap:11px}.appointment-row{display:grid;grid-template-columns:58px minmax(0,1fr) 26px;gap:13px;align-items:center;min-height:112px;padding:15px;border:1px solid var(--owner-line);border-radius:22px;background:var(--owner-card);color:inherit;text-decoration:none}.appointment-time{align-self:stretch;display:flex;flex-direction:column;align-items:center;justify-content:center;border-right:1px solid var(--owner-line);padding-right:12px;color:var(--brand);font-size:17px;font-weight:900;line-height:1.08;text-align:center}.appointment-time small{color:var(--owner-muted);font-size:9px;font-weight:700;margin-top:4px}.appointment-main{min-width:0}.appointment-top{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:7px}.appointment-main strong{display:block;font-size:16px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.appointment-meta{display:flex;align-items:center;gap:6px;color:var(--owner-muted);font-size:12px;line-height:1.45;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.appointment-meta .material-symbols-rounded{font-size:15px;color:var(--brand)}.chevron{color:#786f67;font-size:22px}.pill{display:inline-flex;align-items:center;gap:5px;padding:5px 9px;border-radius:999px;font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.04em;white-space:nowrap;background:rgba(255,255,255,.08);color:var(--owner-muted)}.pill.pending{background:rgba(244,183,64,.13);color:var(--owner-warning)}.pill.confirmed{background:rgba(4,177,85,.13);color:#57d995}.pill.cancelled,.pill.rejected{background:rgba(235,59,90,.12);color:#ff8197}.pill.completed{background:rgba(212,168,79,.15);color:var(--brand)}
        .empty-state{text-align:center;padding:34px 22px;border:1px dashed var(--owner-line);border-radius:24px;background:var(--owner-card);color:var(--owner-muted)}.empty-icon{width:54px;height:54px;margin:0 auto 14px;display:grid;place-items:center;border-radius:18px;background:var(--owner-elevated);color:var(--brand)}.empty-state strong{display:block;color:#fff;font-size:16px;margin-bottom:5px}.empty-state p{margin:0;font-size:13px;line-height:1.45}
        .quick-actions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.quick-action{min-height:92px;padding:13px 8px;border:1px solid var(--owner-line);border-radius:20px;background:var(--owner-card);color:#fff;text-decoration:none;text-align:center;font-size:11px;font-weight:700}.quick-action .material-symbols-rounded{display:grid;place-items:center;width:38px;height:38px;margin:0 auto 8px;border-radius:13px;background:var(--owner-elevated);color:var(--brand)}
        .owner-app .bottom-nav{width:min(100%,760px);grid-template-columns:repeat(5,1fr);padding:8px 8px calc(7px + env(safe-area-inset-bottom));background:rgba(14,12,10,.96);border-color:var(--owner-line);backdrop-filter:blur(20px)}.owner-app .bottom-nav a{display:flex;flex-direction:column;align-items:center;gap:4px;color:#8f867f;font-size:10px;font-weight:700;padding:5px 2px 4px;border-radius:14px}.owner-app .bottom-nav a.active{background:transparent;color:var(--brand)}.owner-app .bottom-nav .material-symbols-rounded{font-size:24px}.owner-app .bottom-nav a.active .material-symbols-rounded{font-variation-settings:'FILL' 1,'wght' 600,'GRAD' 0,'opsz' 24}
        .owner-app .button{min-height:50px;border-radius:18px}.owner-app .button.brand{background:var(--brand);color:#0d0b09}.owner-app .button.primary{background:#fff;color:#0d0b09}.owner-app .button.secondary{border:1px solid var(--owner-line);background:var(--owner-elevated);color:#fff}.owner-app .button.danger{border:1px solid rgba(235,59,90,.28);background:rgba(235,59,90,.12);color:#ff8197}.owner-app .button.success{background:var(--owner-success);color:#fff}.owner-app .field label{color:#fff;font-size:13px}.owner-app .field input,.owner-app .field select{border-color:var(--owner-line);background:#0d0b09;color:#fff}.owner-app .field input:focus,.owner-app .field select:focus{outline:3px solid color-mix(in srgb,var(--brand) 20%,transparent);border-color:var(--brand)}.owner-app .field input[type=date]{color-scheme:dark}.owner-app .muted{color:var(--owner-muted)}
        .date-control{display:flex;align-items:center;gap:10px;margin-bottom:18px;padding:10px 12px;border:1px solid var(--owner-line);border-radius:18px;background:var(--owner-card)}.date-control .material-symbols-rounded{color:var(--brand)}.date-control input{flex:1;border:0;background:transparent;color:#fff;font-weight:700;outline:0;min-height:38px;color-scheme:dark}.date-control button{border:0;background:transparent;color:var(--brand);font-weight:800;cursor:pointer}
        .service-card{display:grid;grid-template-columns:76px minmax(0,1fr) 42px;gap:14px;align-items:center;min-height:108px}.service-image{width:76px;height:76px;border-radius:18px;object-fit:cover;background:var(--owner-elevated)}.service-card h3,.staff-card h3{margin:0 0 7px;font-size:16px}.service-meta{display:flex;flex-wrap:wrap;gap:7px 12px;color:var(--owner-muted);font-size:12px}.service-meta span{display:flex;align-items:center;gap:4px}.service-meta .material-symbols-rounded{font-size:16px;color:var(--brand)}.service-price{margin-top:9px;color:var(--brand);font-size:15px;font-weight:900}.staff-card{display:grid;grid-template-columns:68px minmax(0,1fr);gap:14px;align-items:center}.staff-avatar{width:68px;height:68px;border-radius:20px;object-fit:cover;background:var(--owner-elevated)}.staff-status{display:flex;align-items:center;gap:6px;color:var(--owner-muted);font-size:12px}.staff-status::before{content:"";width:7px;height:7px;border-radius:50%;background:var(--owner-danger)}.staff-status.active::before{background:var(--owner-success)}
        .floating-add{position:fixed;z-index:24;right:max(18px,calc((100vw - 720px)/2 + 18px));bottom:calc(88px + env(safe-area-inset-bottom));width:56px;height:56px;border:0;border-radius:19px;background:var(--brand);color:#0d0b09;display:grid;place-items:center;box-shadow:0 12px 30px rgba(0,0,0,.38);cursor:pointer}.floating-add .material-symbols-rounded{font-size:29px}
        dialog.sheet{width:min(calc(100% - 20px),560px);max-height:88dvh;margin:auto auto 0;padding:0;border:1px solid var(--owner-line);border-radius:28px 28px 0 0;background:var(--owner-surface);color:#fff;box-shadow:0 -20px 60px rgba(0,0,0,.55)}dialog.sheet::backdrop{background:rgba(0,0,0,.72);backdrop-filter:blur(3px)}.sheet-inner{padding:9px 18px calc(22px + env(safe-area-inset-bottom));overflow:auto;max-height:88dvh}.sheet-handle{width:42px;height:4px;border-radius:99px;background:#665d56;margin:0 auto 18px}.sheet-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:20px}.sheet-head h2{margin:0;font-size:23px}.sheet-close{width:40px;height:40px;border:0;border-radius:14px;background:var(--owner-elevated);color:#fff;display:grid;place-items:center;cursor:pointer}.sheet .grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}
        .detail-top{display:flex;align-items:center;gap:12px;margin-bottom:20px}.back-button{width:44px;height:44px;border:1px solid var(--owner-line);border-radius:15px;background:var(--owner-card);color:#fff;display:grid;place-items:center;text-decoration:none}.detail-top h2{font-size:22px;margin:0}.detail-hero{text-align:center;padding:24px 18px}.detail-hero .metric-icon{margin:0 auto 14px;width:58px;height:58px;border-radius:19px}.detail-hero h3{margin:0 0 6px;font-size:22px}.detail-hero p{margin:0;color:var(--owner-muted)}.detail-list{margin-top:12px}.detail-row{display:grid;grid-template-columns:38px minmax(0,1fr);gap:12px;padding:14px 0;border-bottom:1px solid var(--owner-line)}.detail-row:last-child{border-bottom:0}.detail-row>.material-symbols-rounded{color:var(--brand);font-size:21px}.detail-label{display:block;color:var(--owner-muted);font-size:11px;margin-bottom:4px}.detail-value{font-size:15px;font-weight:700}.detail-value a{color:#fff}.detail-actions{display:grid;gap:10px;margin-top:16px}.menu-list{display:grid;gap:10px}.menu-row{display:grid;grid-template-columns:46px minmax(0,1fr) 24px;gap:13px;align-items:center;padding:15px;border:1px solid var(--owner-line);border-radius:20px;background:var(--owner-card);color:#fff;text-decoration:none}.menu-icon{width:46px;height:46px;display:grid;place-items:center;border-radius:15px;background:var(--owner-elevated);color:var(--brand)}.menu-row strong{display:block;font-size:15px}.menu-row small{display:block;color:var(--owner-muted);font-size:11px;margin-top:4px}.logout-button{width:100%;border:0;text-align:left;cursor:pointer}.owner-app .qr{background:#fff;border:10px solid #fff;border-radius:24px}.link-box{display:flex;align-items:center;gap:8px;padding:12px 14px;border:1px solid var(--owner-line);border-radius:16px;background:#0d0b09;color:var(--owner-muted);font-size:12px;overflow:hidden}.link-box span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
        .loading-skeleton{min-height:100px;border-radius:22px;background:var(--owner-card);animation:pulse 1.5s ease-in-out infinite}@keyframes pulse{50%{opacity:.55}}@media(max-width:460px){.grid.two{grid-template-columns:1fr}.slots{grid-template-columns:repeat(2,minmax(0,1fr))}main{padding-left:16px;padding-right:16px}.topbar{padding-left:16px;padding-right:16px}.owner-app main{padding-left:16px;padding-right:16px}.owner-app .topbar{padding-left:16px;padding-right:16px}.owner-app .topbar h1{max-width:200px}.sheet .grid.two{grid-template-columns:1fr}}@media(min-width:700px){dialog.sheet{margin:auto;border-radius:28px}.sheet-inner{padding-bottom:24px}.floating-add{right:calc((100vw - 720px)/2 + 22px)}}@media(display-mode:standalone){.browser-only{display:none}.shell{box-shadow:none}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}.loading-skeleton{animation:none}}
    </style>
    @stack('head')
</head>
<body class="{{ $isOwnerApp ? 'owner-app' : 'customer-app' }}">
<div class="shell">@yield('content')</div>
<script>
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('{{ route('pwa.service-worker') }}').catch(()=>{}));}
window.pwaInstall={deferred:null};
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();window.pwaInstall.deferred=event;document.querySelectorAll('[data-install]').forEach(el=>el.classList.add('visible'));});
window.addEventListener('appinstalled',()=>document.querySelectorAll('[data-install]').forEach(el=>el.classList.remove('visible')));
async function installPwa(){const prompt=window.pwaInstall.deferred;if(!prompt)return;await prompt.prompt();await prompt.userChoice;window.pwaInstall.deferred=null;document.querySelectorAll('[data-install]').forEach(el=>el.classList.remove('visible'));}
function openSheet(id){document.getElementById(id)?.showModal()}
function closeSheet(id){document.getElementById(id)?.close()}
document.addEventListener('click',event=>{if(event.target.tagName==='DIALOG')event.target.close()});
</script>
@stack('scripts')
</body>
</html>
